---
- name: Include variables for RHEL.
  include_vars: "RedHat-7.yml"
  
- name: Define java_packages.
  set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined

- include_tasks: setup-RedHat.yml

- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home != ''

- name: check java version
  command: java -version
  changed_when: false
  register: javaversion

- debug: var=javaversion
