---
# Variable setup.
- name: Include variables.
  include_vars: RedHat.yml

- name: Define php_mysql_package.
  set_fact:
    php_mysql_package: "{{ __php_mysql_package }}"
  when: php_mysql_package is not defined

# Installation.
- name: Install PHP MySQL dependencies.
  yum:
    name: "{{ php_mysql_package }}"
    state: present
    enablerepo: "{{ php_enablerepo }}"
  notify:
    - restart webserver
    - restart php-fpm